name: grepify-postgres
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: grepify
      POSTGRES_USER: grepify
      POSTGRES_DB: grepify
    ports:
      - 5432:5432
