/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A runnable Grepify app. */
export declare class AppJs {
  /** Open an app with its own single-app environment at `dbPath`. */
  static open(name: string, options?: EnvironmentOptions | undefined | null): Promise<AppJs>
  /** The app name (its LMDB namespace). */
  get name(): string
  /**
   * Start an update, running `appMain` as the root pipeline function.
   * Returns a handle for awaiting completion / polling stats.
   */
  startUpdate(appMain: (ctx: CtxJs) => Promise<Buffer>): UpdateHandleJs
  /**
   * Run `appMain` to completion and return its result bytes. Convenience over
   * `startUpdate(...).result()`.
   */
  update(appMain: (ctx: CtxJs) => Promise<Buffer>): Promise<Buffer>
  /** Start dropping all persisted app state (LMDB data). Irreversible. */
  startDrop(): DropHandleJs
  /** Drop all persisted app state and await completion. */
  dropState(): Promise<void>
}

/** Pipeline context handed to JS processors. Wraps `grepify::Ctx`. */
export declare class CtxJs {
  /**
   * Whether this context is running inside an active `App.update()` pipeline
   * (i.e. LMDB memoization / target states are available).
   */
  hasPipelineContext(): boolean
  /**
   * Mount a single child component under `key` and return its result bytes.
   *
   * `memoKey` (msgpack) enables component-level memoization: on an unchanged
   * key the engine skips running `processor` entirely. Mirrors `useMount`.
   */
  useMount(key: string, memoKey: Buffer | undefined | null, processor: (ctx: CtxJs) => Promise<Buffer>): Promise<Buffer>
  /**
   * Mount a named sub-component (child scope) with no memoization. Mirrors
   * `Ctx::scope` / `componentSubpath` + `mount`.
   */
  scope(key: string, processor: (ctx: CtxJs) => Promise<Buffer>): Promise<Buffer>
  /**
   * Mount one child component per `(key, value)` item, all concurrently, and
   * return their result bytes in order. Mirrors `mountEach`.
   */
  mountEach(items: Array<MountItem>, processor: (ctx: CtxJs, value: Buffer) => Promise<Buffer>): Promise<Buffer[]>
  /**
   * Cached computation keyed by `keyBytes` (msgpack). If the key is unchanged
   * since the last run, returns the cached bytes without invoking
   * `processor`. Mirrors `Ctx::memo`.
   */
  memo(keyBytes: Buffer, processor: (ctx: CtxJs) => Promise<Buffer>): Promise<Buffer>
  /**
   * Declare a persistent per-component state initialized to `initialValue`
   * (msgpack) on first run. Mirrors `useState` / `Ctx::use_state`.
   */
  useState(key: string, initialValue: Buffer): StateHandleJs
}

/**
 * A declarative directory target. Files you `declareFile` are reconciled
 * against the previous run: new/changed files written, unchanged skipped,
 * orphaned files deleted.
 */
export declare class DirTarget {
  /** The target directory path. */
  get dir(): string
  /**
   * Declare that `name` (a relative path under the target dir) should hold
   * `content`. The write/skip/delete is decided by the engine at reconcile.
   */
  declareFile(ctx: CtxJs, name: string, content: Buffer): void
}
export type DirTargetJs = DirTarget

/** Handle for a running drop-state operation. */
export declare class DropHandleJs {
  /** A point-in-time, per-component stats snapshot. */
  stats(): UpdateStatsJs
  /** Drive the drop to completion. */
  result(): Promise<void>
}

/** A Grepify environment: the LMDB store shared by apps built from it. */
export declare class EnvironmentJs {
  /**
   * Open (or create) an environment at the given `dbPath` with LMDB settings.
   *
   * Opening the same db path more than once in a process returns a cached
   * handle (LMDB forbids a second open); LMDB options on later opens of the
   * same path are ignored.
   */
  static open(options?: EnvironmentOptions | undefined | null): Promise<EnvironmentJs>
  /** Create an app in this environment. Each `name` is its own LMDB namespace. */
  app(name: string): Promise<AppJs>
}

/**
 * A walked file with a stable key and lazy content access — the napi mirror of
 * `grepify::fs::FileEntry`.
 */
export declare class FileEntryJs {
  /** Stable key for component paths (relative path, forward slashes). */
  get key(): string
  /** Relative path from the walk root (forward slashes). */
  get relativePath(): string
  /** Full filesystem path. */
  get path(): string
  /** File stem (name without extension). */
  get stem(): string
  /** Read the file contents as raw bytes. */
  content(): Buffer
  /** Read the file contents as a UTF-8 string (BOM-aware, lossy decode). */
  contentStr(): string
}

/**
 * A handle to a custom JS target: declare rows on it, then let the engine
 * reconcile them via your `applyActions` callback.
 */
export declare class JsTarget {
  /**
   * Declare that row `key` should hold `value` (msgpack `Buffer`). The engine
   * decides upsert/skip/delete during reconciliation and batches the results
   * into your `applyActions` callback. Rows no longer declared are deleted.
   */
  declareRow(ctx: CtxJs, key: string, value: Buffer): void
}
export type JsTargetJs = JsTarget

/**
 * A token-bucket rate limiter. `acquire(n)` returns a Promise that resolves
 * once `n` tokens are available; concurrent callers are served FIFO.
 */
export declare class RateLimiter {
  /**
   * Create a limiter allowing `maxRowsPerSecond`, with burst capacity sized
   * to `burstWindowSecs` (default 1s, matching the Python default).
   */
  constructor(maxRowsPerSecond: number, burstWindowSecs?: number | undefined | null)
  /** Wait until `n` tokens are available (default 1). */
  acquire(n?: number | undefined | null): Promise<void>
}
export type RateLimiterJs = RateLimiter

/**
 * Handle to a persistent component state. `get()` returns the current bytes;
 * `set(bytes)` persists new bytes for the next run.
 */
export declare class StateHandleJs {
  /** The current value bytes (msgpack). */
  get(): Buffer
  /** Persist `value` (msgpack) as the state for the next run. */
  set(value: Buffer): void
}

/**
 * Handle for a running update: await [`result`], poll [`stats`], or wait for
 * the next change via [`changed`].
 */
export declare class UpdateHandleJs {
  /** A point-in-time, per-component stats snapshot. */
  stats(): UpdateStatsJs
  /**
   * Wait for the update to advance; resolves to `true` when it is still
   * running and `false` once it has terminated (mirrors `watch()`).
   */
  changed(): Promise<boolean>
  /** Drive the update to completion and return `appMain`'s result bytes. */
  result(): Promise<Buffer>
}

/**
 * Cancel the global cancellation token, causing all in-flight operations to
 * exit promptly. Safe to call from signal handlers (e.g. a Ctrl+C hook).
 */
export declare function cancelAllJs(): void

export interface ChunkJs {
  startByte: number
  endByte: number
  startCharOffset: number
  startLine: number
  startColumn: number
  endCharOffset: number
  endLine: number
  endColumn: number
}

export interface CodeMatchJs {
  kind: string
  chunks: Array<ChunkJs>
  captures: Record<string, Array<ChunkJs>>
}

/** Per-component statistics snapshot (mirrors Python's `UpdateHandle.stats()`). */
export interface ComponentStatsJs {
  numExecutionStarts: number
  numUnchanged: number
  numAdds: number
  numDeletes: number
  numReprocesses: number
  numErrors: number
}

export declare function detectCodeLanguageJs(filename: string): string | null

/** LMDB / concurrency settings for an [`EnvironmentJs`]. */
export interface EnvironmentOptions {
  /** LMDB database directory (default: `./coco_state`). */
  dbPath?: string
  /** LMDB maximum number of named databases. */
  lmdbMaxDbs?: number
  /** LMDB map size in bytes. */
  lmdbMapSize?: number
  /** Limit the number of concurrently processing components per app. */
  maxInflightComponents?: number
}

/**
 * Fingerprint raw (already-canonicalized, e.g. msgpack) bytes, returning the
 * base64 fingerprint string used across Grepify hosts.
 */
export declare function fingerprintBytes(data: Buffer): string

/** Detailed info for one stable path (as `pathBytes` from `iterStablePaths`). */
export declare function getStablePathDetail(app: AppJs, pathBytes: Buffer): Promise<StablePathDetailJs | null>

/** Detailed info for one path of an app by name. */
export declare function getStablePathDetailByName(env: EnvironmentJs, appName: string, pathBytes: Buffer): Promise<StablePathDetailJs | null>

export declare function indexTerms(source: string, language: string, minLen: number): Array<string>

/**
 * Initialize the shared engine runtime. Idempotent — the runtime is a lazy
 * global, so this simply forces it up front (analogous to Python's
 * `init_runtime`, minus the pickle serializer injection which the TS host does
 * not use: JS values are msgpack-encoded on the JS side).
 */
export declare function initRuntime(): void

/**
 * All stable paths for `app`, with node-type metadata (mirrors Python's
 * `iter_stable_paths`, collected eagerly).
 */
export declare function iterStablePaths(app: AppJs): Promise<Array<StablePathInfoJs>>

/**
 * Stable paths (with metadata) for an app by name (opens read-only; empty if
 * the app does not exist).
 */
export declare function iterStablePathsByName(env: EnvironmentJs, appName: string): Promise<Array<StablePathInfoJs>>

/**
 * One reconciled change handed to the JS `applyActions` callback. `value` is
 * present for an upsert (create/update) and `null` for a delete.
 */
export interface JsTargetAction {
  /** `"upsert"` or `"delete"`. */
  kind: string
  /**
   * The declared row key (the raw string for a string key; otherwise the
   * engine's `StableKey` display form).
   */
  key: string
  /** The declared row value (msgpack `Buffer`), or `null` for a delete. */
  value?: Buffer
}

/** Names of all apps with persisted state in this environment. */
export declare function listAppNames(env: EnvironmentJs): Promise<Array<string>>

export declare function matchCode(pattern: string, source: string, language: string): Array<CodeMatchJs>

/**
 * Mount a declarative directory target rooted at `dir`. Must be called inside
 * an `App.update()` pipeline (uses the current component context).
 */
export declare function mountDirTarget(ctx: CtxJs, dir: string): DirTarget

/**
 * One `(key, value)` item for `mountEach`, with an optional precomputed
 * component-memo key (the TS `fn()` wrapper folds logic hash + input
 * fingerprint into `memoKey`).
 */
export interface MountItem {
  key: string
  value: Buffer
  /**
   * msgpack bytes of the memo key; when present, an unchanged key lets the
   * engine skip re-running the whole child component.
   */
  memoKey?: Buffer
}

/**
 * Mount a custom JS target rooted at the unique `name`. `applyActions` is
 * invoked (async) with each reconciled batch of upserts/deletes. Must be called
 * inside an `App.update()` pipeline.
 */
export declare function mountJsTarget(ctx: CtxJs, name: string, applyActions: (actions: Array<JsTargetAction>) => Promise<void>): JsTarget

/** Provider generation info for a target-state item. */
export interface ProviderGenerationJs {
  providerId: number
  providerSchemaVersion: number
}

/** Query detail for a path and (optionally) its children/parents. */
export declare function queryStablePathDetails(app: AppJs, pathBytes: Buffer, includeChildren: boolean, recursive: boolean, includeParents: boolean): Promise<Array<StablePathDetailJs>>

/** Query detail for a path (and optionally children/parents) of an app by name. */
export declare function queryStablePathDetailsByName(env: EnvironmentJs, appName: string, pathBytes: Buffer, includeChildren: boolean, recursive: boolean, includeParents: boolean): Promise<Array<StablePathDetailJs>>

export interface RecursiveChunkConfigJs {
  chunkSize: number
  minChunkSize?: number
  chunkOverlap?: number
  language?: string
}

/**
 * Replace the cancelled global token with a fresh one so new operations can
 * proceed. Call at the start of each CLI command / fresh run.
 */
export declare function resetGlobalCancellationJs(): void

/** The msgpack encoding of the LMDB root path (`/`), for querying from the top. */
export declare function rootStablePath(): Buffer

export declare function splitTextRecursive(source: string, config: RecursiveChunkConfigJs): Array<ChunkJs>

/** Detailed info about a single stable path stored in LMDB. */
export interface StablePathDetailJs {
  path: string
  pathBytes: Buffer
  nodeType: string
  version: number
  processorName: string
  targetStateCount: number
  hasMemoization: boolean
  targetStateItems: Array<TargetStateInfoItemSummaryJs>
}

/**
 * A stable path plus its node-type. `pathBytes` round-trips into the detail /
 * query functions.
 */
export interface StablePathInfoJs {
  /** Human-readable path (e.g. `/"process"/"a.md"`). */
  path: string
  /** Opaque msgpack encoding of the path; pass back to `getStablePathDetail`. */
  pathBytes: Buffer
  /** `"Directory"` or `"Component"`. */
  nodeType: string
}

/** Per-item summary of a target-state entry at a stable path. */
export interface TargetStateInfoItemSummaryJs {
  targetStatePath: string
  /** Human-readable stable key. */
  key: string
  /** Opaque msgpack encoding of the key. */
  keyBytes: Buffer
  states: Array<TargetStateVersionJs>
  providerSchemaVersion: number
  providerGeneration?: ProviderGenerationJs
}

/** Version + state label for one target-state entry. */
export interface TargetStateVersionJs {
  version: number
  state: string
}

export interface TextPositionJs {
  byteOffset: number
  charOffset: number
  line: number
  column: number
}

/** A detailed update-stats snapshot. */
export interface UpdateStatsJs {
  ready: boolean
  byComponent: Record<string, ComponentStatsJs>
}

export declare function version(): string

/**
 * Walk a directory and return the matching files (sorted by relative path).
 *
 * Mirrors `grepify::fs::walk_dir(path).recursive(..).path_matcher(..)`.
 */
export declare function walkDirJs(path: string, options?: WalkOptions | undefined | null): Array<FileEntryJs>

/** Options controlling a `walkDir` traversal. */
export interface WalkOptions {
  /** Recurse into subdirectories (default: false). */
  recursive?: boolean
  /** Glob patterns to include. When omitted, all files match. */
  includedPatterns?: Array<string>
  /** Glob patterns to exclude. Supports gitignore-style `!` negations. */
  excludedPatterns?: Array<string>
}
